name: tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cctools_osx-arm64=973.0.1
  - certifi=2024.2.2
  - clang=12.0.1
  - clang-12=12.0.1
  - clang_osx-arm64=12.0.1
  - clangxx=12.0.1
  - clangxx_osx-arm64=12.0.1
  - colorama=0.4.6
  - compiler-rt=12.0.1
  - compiler-rt_osx-arm64=12.0.1
  - contourpy=1.2.1
  - cycler=0.12.1
  - filelock=3.13.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - h5py=3.10.0
  - hdf5=1.14.3
  - importlib-metadata=7.1.0
  - jinja2=3.1.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld64_osx-arm64=609
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp12=12.0.1
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgpuarray=0.7.6
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm12=12.0.1
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libprotobuf=4.25.1
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libtorch=2.1.2
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - llvm-tools=12.0.1
  - mako=1.3.2
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - networkx=3.3
  - nomkl=1.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.2.1
  - pillow=10.3.0
  - pip=24.0
  - pthread-stubs=0.4
  - pygpu=0.7.6
  - pyparsing=3.1.2
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.1.2
  - pytorch-model-summary=0.1.1
  - pytz=2024.1
  - readline=8.2
  - scipy=1.13.0
  - setuptools=69.2.0
  - sigtool=0.1.3
  - six=1.16.0
  - sleef=3.5.1
  - sympy=1.12
  - tapi=1100.0.11
  - theano=1.0.5
  - tk=8.6.13
  - torchfile=0.1.0
  - tornado=6.4
  - tqdm=4.66.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
